package constants

var DRIVER_SEARCH = "DRIVER_SEARCH"
var DRIVER_FOUND = "DRIVER_FOUND"
var ON_POSITION = "ON_POSITION"
var STARTED = "STARTED"
var ENDED = "ENDED"
var CANCELED = "CANCELED"

var PORT_TOPIC_DRIVER = "29092"
